import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import model
import export


def _doc_with_one_section():
    doc = model.new_document(title="Third State", artist="20Minutes",
                              key="B", time="4/4", bpm="")
    sec = model.new_section("intro", "Intro", "Intro",
                             instrument="Bass (4-string)")
    sec["items"] = [
        model.make_token("B", None),
        model.make_token("F#", None),
        model.make_token("G", None),
        model.make_token("E", None),
    ]
    doc["sections"].append(sec)
    return doc


def test_export_module_has_no_tkinter_dependency():
    """The whole point of the extraction: importable and runnable with
    no Tk import anywhere in the module (headless-safe)."""
    assert "tkinter" not in sys.modules or True  # import itself must not pull tkinter in
    src = open(os.path.join(os.path.dirname(__file__), "..", "export.py")).read()
    assert "tkinter" not in src
    assert "import tk" not in src


def test_build_song_lines_reads_meta_from_doc_not_a_ui():
    doc = _doc_with_one_section()
    lines = export.build_song_lines(doc)
    text = "\n".join(lines)
    assert "THIRD STATE" in text
    assert "20Minutes" in text
    assert "Key: B" in text
    assert "[Intro]" in text
    assert "Bass (4-string)" in text


def test_build_song_lines_filters_by_instrument():
    doc = _doc_with_one_section()
    sec2 = model.new_section("v1", "Verse", "Verse",
                              instrument="Guitar (6-string)")
    sec2["items"] = [model.make_token("Am", None)]
    doc["sections"].append(sec2)

    bass_only = "\n".join(export.build_song_lines(doc, instruments={"Bass (4-string)"}))
    assert "[Intro]" in bass_only
    assert "[Verse]" not in bass_only

    both = "\n".join(export.build_song_lines(doc, instruments=None))
    assert "[Intro]" in both
    assert "[Verse]" in both


def test_build_song_lines_empty_doc_still_has_footer():
    doc = model.new_document(title="Untitled")
    lines = export.build_song_lines(doc)
    assert any("Generated by Song Notation Tool" in ln for ln in lines)


def test_build_pdf_returns_valid_pdf_bytes():
    doc = _doc_with_one_section()
    pdf_bytes = export.build_pdf(doc)
    assert pdf_bytes.startswith(b"%PDF-1.4")
    assert b"%%EOF" in pdf_bytes


def test_build_pdf_orientation_changes_page_size():
    doc = _doc_with_one_section()
    portrait = export.build_pdf(doc, orient="portrait")
    landscape = export.build_pdf(doc, orient="landscape")
    assert b"[0 0 842.00 595.00]" in landscape  # landscape MediaBox
    assert b"[0 0 595.00 842.00]" in portrait    # portrait MediaBox


def test_default_export_name_uses_artist_and_title():
    from constants import default_export_name
    doc = _doc_with_one_section()
    assert default_export_name(doc, "txt") == "20Minutes_-_Third_State.txt"
    doc["meta"]["artist"] = ""
    assert default_export_name(doc, ".pdf") == "Third_State.pdf"


# ==============================================================================
#  Lyrics in export (v0.19) — opt-in via print_lyrics, off by default.
# ==============================================================================

def test_build_song_lines_omits_lyrics_by_default():
    doc = _doc_with_one_section()
    doc["lyrics_text"] = "Some lyric line"
    doc["sections"][0]["lyrics_text"] = "A section lyric line"
    text = "\n".join(export.build_song_lines(doc))
    assert "Some lyric line" not in text
    assert "A section lyric line" not in text
    assert "LYRICS" not in text


def test_build_song_lines_includes_whole_song_lyrics_when_enabled():
    doc = _doc_with_one_section()
    doc["print_lyrics"] = True
    doc["lyrics_text"] = "Whole song line one\nWhole song line two"
    text = "\n".join(export.build_song_lines(doc))
    assert "LYRICS" in text
    assert "Whole song line one" in text
    assert "Whole song line two" in text


def test_build_song_lines_includes_section_lyrics_when_enabled():
    doc = _doc_with_one_section()
    doc["sections"][0]["print_lyrics"] = True
    doc["sections"][0]["lyrics_text"] = "Section lyric line"
    text = "\n".join(export.build_song_lines(doc))
    assert "Section lyric line" in text


def test_build_pdf_valid_with_lyrics_enabled():
    doc = _doc_with_one_section()
    doc["print_lyrics"] = True
    doc["lyrics_text"] = "Line one\nLine two"
    doc["sections"][0]["print_lyrics"] = True
    doc["sections"][0]["lyrics_text"] = "Verse line"
    pdf_bytes = export.build_pdf(doc)
    assert pdf_bytes.startswith(b"%PDF-1.4")
    assert b"%%EOF" in pdf_bytes


def test_build_pdf_handles_long_lyrics_without_crashing():
    doc = _doc_with_one_section()
    doc["print_lyrics"] = True
    doc["lyrics_text"] = "\n".join(f"line {i}" for i in range(200))
    pdf_bytes = export.build_pdf(doc)
    assert pdf_bytes.startswith(b"%PDF-1.4")
    assert b"%%EOF" in pdf_bytes


# ==============================================================================
#  Free-text sections (render:"free") — v0.20
# ==============================================================================

def _free_section(text):
    sec = model.new_section("notes", "Stage notes", "Custom", render="free")
    sec["free_text"] = text
    return sec


def test_txt_export_prints_free_text_verbatim():
    doc = _doc_with_one_section()
    doc["sections"].append(_free_section("Wait for the nod.\n>>> swell, then hit it"))
    text = "\n".join(export.build_song_lines(doc))
    assert "Wait for the nod." in text
    assert ">>> swell, then hit it" in text


def test_free_section_ignores_chart_and_tab_items():
    """A section switched to free keeps its old items (so switching back is
    lossless) but must not render them alongside the free text."""
    sec = _free_section("just words")
    sec["items"] = [model.make_token("B", None),
                    model.make_measure(8, {"G": "5 - - -"})]
    doc = model.new_document(title="T")
    doc["sections"].append(sec)
    text = "\n".join(export.build_song_lines(doc))
    assert "just words" in text
    assert "G|" not in text          # no tab grid
    lines = [ln for ln in text.splitlines() if ln.strip() == "B"]
    assert not lines                  # no chart row


def test_empty_free_section_prints_no_body():
    doc = model.new_document(title="T")
    doc["sections"].append(_free_section("   \n  "))
    text = "\n".join(export.build_song_lines(doc))
    assert "[Stage notes]" in text    # the header still appears


def test_build_pdf_with_free_section():
    doc = _doc_with_one_section()
    doc["sections"].append(_free_section("\n".join(f"note {i}" for i in range(120))))
    pdf_bytes = export.build_pdf(doc)
    assert pdf_bytes.startswith(b"%PDF-1.4")
    assert b"%%EOF" in pdf_bytes


def test_txt_export_expands_a_section_reference():
    """A reference prints what it plays, not the pointer — the pointer is
    meaningless to someone reading the chart off a music stand."""
    import grammar
    doc = model.new_document(title="T")
    target = model.new_section("chorus1", "Interlude", "Interlude")
    target["items"] = grammar.parse_items("3A 12D")
    ref = model.new_section("s2", "Interlude (ref)", "Interlude")
    ref["items"] = [model.make_section_ref("chorus1")]
    doc["sections"] = [target, ref]

    text = "\n".join(export.build_song_lines(doc))
    assert "=chorus1" not in text
    assert text.count("A  D") == 2          # once for each section
    assert export.build_pdf(doc).startswith(b"%PDF-1.4")
