import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import model
import export


def _doc_with_one_section():
    doc = model.new_document(title="Third State", artist="20Minutes",
                              key="B", time="4/4", bpm="")
    sec = model.new_section("intro", "Intro", "Intro",
                             instrument="Bass (4-string)")
    sec["items"] = [
        model.make_token("B", None),
        model.make_token("F#", None),
        model.make_token("G", None),
        model.make_token("E", None),
    ]
    doc["sections"].append(sec)
    return doc


def test_export_module_has_no_tkinter_dependency():
    """The whole point of the extraction: importable and runnable with
    no Tk import anywhere in the module (headless-safe)."""
    assert "tkinter" not in sys.modules or True  # import itself must not pull tkinter in
    src = open(os.path.join(os.path.dirname(__file__), "..", "export.py")).read()
    assert "tkinter" not in src
    assert "import tk" not in src


def test_build_song_lines_reads_meta_from_doc_not_a_ui():
    doc = _doc_with_one_section()
    lines = export.build_song_lines(doc)
    text = "\n".join(lines)
    assert "THIRD STATE" in text
    assert "20Minutes" in text
    assert "Key: B" in text
    assert "[Intro]" in text
    assert "Bass (4-string)" in text


def test_build_song_lines_filters_by_instrument():
    doc = _doc_with_one_section()
    sec2 = model.new_section("v1", "Verse", "Verse",
                              instrument="Guitar (6-string)")
    sec2["items"] = [model.make_token("Am", None)]
    doc["sections"].append(sec2)

    bass_only = "\n".join(export.build_song_lines(doc, instruments={"Bass (4-string)"}))
    assert "[Intro]" in bass_only
    assert "[Verse]" not in bass_only

    both = "\n".join(export.build_song_lines(doc, instruments=None))
    assert "[Intro]" in both
    assert "[Verse]" in both


def test_build_song_lines_empty_doc_still_has_footer():
    doc = model.new_document(title="Untitled")
    lines = export.build_song_lines(doc)
    assert any("Generated by Song Notation Tool" in ln for ln in lines)


def test_build_pdf_returns_valid_pdf_bytes():
    doc = _doc_with_one_section()
    pdf_bytes = export.build_pdf(doc)
    assert pdf_bytes.startswith(b"%PDF-1.4")
    assert b"%%EOF" in pdf_bytes


def test_build_pdf_orientation_changes_page_size():
    doc = _doc_with_one_section()
    portrait = export.build_pdf(doc, orient="portrait")
    landscape = export.build_pdf(doc, orient="landscape")
    assert b"[0 0 842.00 595.00]" in landscape  # landscape MediaBox
    assert b"[0 0 595.00 842.00]" in portrait    # portrait MediaBox


def test_default_export_name_uses_artist_and_title():
    from constants import default_export_name
    doc = _doc_with_one_section()
    assert default_export_name(doc, "txt") == "20Minutes_-_Third_State.txt"
    doc["meta"]["artist"] = ""
    assert default_export_name(doc, ".pdf") == "Third_State.pdf"


# ==============================================================================
#  Lyrics in export (v0.19) — opt-in via print_lyrics, off by default.
# ==============================================================================

def test_build_song_lines_omits_lyrics_by_default():
    doc = _doc_with_one_section()
    doc["lyrics_text"] = "Some lyric line"
    doc["sections"][0]["lyrics_text"] = "A section lyric line"
    text = "\n".join(export.build_song_lines(doc))
    assert "Some lyric line" not in text
    assert "A section lyric line" not in text
    assert "LYRICS" not in text


def test_build_song_lines_includes_whole_song_lyrics_when_enabled():
    doc = _doc_with_one_section()
    doc["print_lyrics"] = True
    doc["lyrics_text"] = "Whole song line one\nWhole song line two"
    text = "\n".join(export.build_song_lines(doc))
    assert "LYRICS" in text
    assert "Whole song line one" in text
    assert "Whole song line two" in text


def test_build_song_lines_includes_section_lyrics_when_enabled():
    doc = _doc_with_one_section()
    doc["sections"][0]["print_lyrics"] = True
    doc["sections"][0]["lyrics_text"] = "Section lyric line"
    text = "\n".join(export.build_song_lines(doc))
    assert "Section lyric line" in text


def test_build_pdf_valid_with_lyrics_enabled():
    doc = _doc_with_one_section()
    doc["print_lyrics"] = True
    doc["lyrics_text"] = "Line one\nLine two"
    doc["sections"][0]["print_lyrics"] = True
    doc["sections"][0]["lyrics_text"] = "Verse line"
    pdf_bytes = export.build_pdf(doc)
    assert pdf_bytes.startswith(b"%PDF-1.4")
    assert b"%%EOF" in pdf_bytes


def test_build_pdf_handles_long_lyrics_without_crashing():
    doc = _doc_with_one_section()
    doc["print_lyrics"] = True
    doc["lyrics_text"] = "\n".join(f"line {i}" for i in range(200))
    pdf_bytes = export.build_pdf(doc)
    assert pdf_bytes.startswith(b"%PDF-1.4")
    assert b"%%EOF" in pdf_bytes


# ==============================================================================
#  Free-text sections (render:"free") — v0.20
# ==============================================================================

def _free_section(text):
    sec = model.new_section("notes", "Stage notes", "Custom", render="free")
    sec["free_text"] = text
    return sec


def test_txt_export_prints_free_text_verbatim():
    doc = _doc_with_one_section()
    doc["sections"].append(_free_section("Wait for the nod.\n>>> swell, then hit it"))
    text = "\n".join(export.build_song_lines(doc))
    assert "Wait for the nod." in text
    assert ">>> swell, then hit it" in text


def test_free_section_ignores_chart_and_tab_items():
    """A section switched to free keeps its old items (so switching back is
    lossless) but must not render them alongside the free text."""
    sec = _free_section("just words")
    sec["items"] = [model.make_token("B", None),
                    model.make_measure(8, {"G": "5 - - -"})]
    doc = model.new_document(title="T")
    doc["sections"].append(sec)
    text = "\n".join(export.build_song_lines(doc))
    assert "just words" in text
    assert "G|" not in text          # no tab grid
    lines = [ln for ln in text.splitlines() if ln.strip() == "B"]
    assert not lines                  # no chart row


def test_empty_free_section_prints_no_body():
    doc = model.new_document(title="T")
    doc["sections"].append(_free_section("   \n  "))
    text = "\n".join(export.build_song_lines(doc))
    assert "[Stage notes]" in text    # the header still appears


def test_build_pdf_with_free_section():
    doc = _doc_with_one_section()
    doc["sections"].append(_free_section("\n".join(f"note {i}" for i in range(120))))
    pdf_bytes = export.build_pdf(doc)
    assert pdf_bytes.startswith(b"%PDF-1.4")
    assert b"%%EOF" in pdf_bytes


def test_txt_export_expands_a_section_reference():
    """A reference prints what it plays, not the pointer — the pointer is
    meaningless to someone reading the chart off a music stand."""
    import grammar
    doc = model.new_document(title="T")
    target = model.new_section("chorus1", "Interlude", "Interlude")
    target["items"] = grammar.parse_items("3A 12D")
    ref = model.new_section("s2", "Interlude (ref)", "Interlude")
    ref["items"] = [model.make_section_ref("chorus1")]
    doc["sections"] = [target, ref]

    text = "\n".join(export.build_song_lines(doc))
    assert "=chorus1" not in text
    assert text.count("A  D") == 2          # once for each section
    assert export.build_pdf(doc).startswith(b"%PDF-1.4")


def test_free_text_and_chart_sections_share_one_left_margin():
    """The reported symptom: a referenced (chart) section printed two
    columns further right than the free-text sections around it."""
    import grammar, render
    doc = model.new_document(title="T")
    free = model.new_section("i", "Intro", "Intro", render="free")
    free["free_text"] = "|--|3-|  |--|5-|"
    chart = model.new_section("c", "Chorus", "Chorus")
    chart["items"] = grammar.parse_items("C G")
    chart["annotation"] = "keep it simple"
    doc["sections"] = [free, chart]

    body = [ln for ln in export.build_song_lines(doc)
            if ln.strip() and not set(ln.strip()) <= {"=", "-"}]
    indents = {len(ln) - len(ln.lstrip()) for ln in body}
    assert indents == {render.BODY_INDENT}


# ==============================================================================
#  Section layout — v0.20
# ==============================================================================

def _layout_doc():
    import grammar
    doc = model.new_document(title="T")
    a = model.new_section("i", "Intro", "Intro", render="free")
    a["free_text"] = "|--|3-|"
    b = model.new_section("v", "Verse 1", "Verse", repeat=2)
    b["items"] = grammar.parse_items("C G")
    doc["sections"] = [a, b]
    return doc


def test_banner_layout_is_the_default_and_keeps_the_header_band():
    doc = _layout_doc()
    text = "\n".join(export.build_song_lines(doc))
    assert "[Intro]" in text and "[Verse 1]" in text


def test_gutter_layout_puts_the_name_beside_the_first_line():
    doc = _layout_doc()
    doc["section_layout"] = "gutter"
    lines = export.build_song_lines(doc)
    intro = next(ln for ln in lines if ln.startswith("Intro"))
    assert "|--|3-|" in intro
    verse = next(ln for ln in lines if ln.startswith("Verse 1"))
    assert "(x2)" in verse and "C" in verse
    assert "[Intro]" not in "\n".join(lines)     # no banner


def test_gutter_layout_is_shorter_than_the_banner_it_replaces():
    doc = _layout_doc()
    banner = len(export.build_song_lines(doc))
    doc["section_layout"] = "gutter"
    assert len(export.build_song_lines(doc)) < banner


def test_both_layouts_build_a_valid_pdf():
    doc = _layout_doc()
    for layout in ("banner", "gutter"):
        doc["section_layout"] = layout
        assert export.build_pdf(doc).startswith(b"%PDF-1.4")


# ==============================================================================
#  Colour and page-fill — v0.20
# ==============================================================================

def test_section_color_is_per_type_and_collapses_in_bw():
    from constants import section_color, SECTION_COLORS
    assert section_color("Solo") == SECTION_COLORS["Solo"]
    assert section_color("Verse") != section_color("Solo")
    assert section_color("Solo", "bw") == (0.0, 0.0, 0.0)
    assert section_color("Solo", "bw") == section_color("Verse", "bw")


def test_an_unknown_section_type_still_gets_a_colour():
    from constants import section_color, DEFAULT_SECTION_COLOR
    assert section_color("Something Else") == DEFAULT_SECTION_COLOR


def test_both_colour_modes_build_a_valid_pdf():
    doc = _layout_doc()
    for mode in ("color", "bw"):
        doc["color_mode"] = mode
        assert export.build_pdf(doc).startswith(b"%PDF-1.4")


def test_fit_scales_a_short_chart_up():
    doc = _layout_doc()
    doc["pdf_scale"] = "fit"
    assert export.resolve_scale(doc, None, "portrait") > 1.0


def test_fit_never_adds_a_page():
    """The whole contract of fit: bigger type, same page count."""
    doc = _layout_doc()
    base = export._build_pdf(doc, None, "portrait", 1.0)[1]
    scale = export.resolve_scale(doc, None, "portrait")
    assert export._build_pdf(doc, None, "portrait", scale)[1] <= base


def test_fit_respects_the_page_width():
    """A long line is what caps the scale — scaled type must not run off
    the side of the paper, which no page count would catch."""
    import grammar
    doc = model.new_document(title="T")
    wide = model.new_section("w", "Wide", "Verse", render="free")
    wide["free_text"] = "|--|12-|  " * 12
    doc["sections"] = [wide]
    scale = export.resolve_scale(doc, None, "portrait")
    longest = max(len(ln) for ln in export._body_lines_for_width(doc, None))
    assert scale < 1.0                                    # shrank to fit
    assert scale >= export.MIN_FIT_SCALE
    assert longest * 4.6 * scale <= (595 - 2 * 28) + 0.5


def test_explicit_scales_are_honoured_and_junk_falls_back_to_fit():
    doc = _layout_doc()
    doc["pdf_scale"] = "1.5"
    assert export.resolve_scale(doc, None, "portrait") == 1.5
    doc["pdf_scale"] = "150%"
    assert export.resolve_scale(doc, None, "portrait") == 1.5
    doc["pdf_scale"] = "normal"
    assert export.resolve_scale(doc, None, "portrait") == 1.0
    doc["pdf_scale"] = "nonsense"
    assert export.resolve_scale(doc, None, "portrait") > 1.0   # fell back to fit


def test_scaling_does_not_change_the_txt_export():
    """Scale and colour are PDF concerns; the TXT chart is plain text."""
    doc = _layout_doc()
    a = export.build_song_lines(doc)
    doc["pdf_scale"] = "2.0"; doc["color_mode"] = "bw"
    assert export.build_song_lines(doc) == a


def test_fit_will_not_shrink_past_legibility():
    """A chart too wide to fit even at the floor stops at the floor rather
    than disappearing — landscape is the real answer at that point."""
    doc = model.new_document(title="T")
    wide = model.new_section("w", "Wide", "Verse", render="free")
    wide["free_text"] = "|--|12-|  " * 60
    doc["sections"] = [wide]
    assert export.resolve_scale(doc, None, "portrait") == export.MIN_FIT_SCALE
