import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import model
import export


def _doc_with_one_section():
    doc = model.new_document(title="Third State", artist="20Minutes",
                              key="B", time="4/4", bpm="")
    sec = model.new_section("intro", "Intro", "Intro",
                             instrument="Bass (4-string)")
    sec["items"] = [
        model.make_token("B", None),
        model.make_token("F#", None),
        model.make_token("G", None),
        model.make_token("E", None),
    ]
    doc["sections"].append(sec)
    return doc


def test_export_module_has_no_tkinter_dependency():
    """The whole point of the extraction: importable and runnable with
    no Tk import anywhere in the module (headless-safe)."""
    assert "tkinter" not in sys.modules or True  # import itself must not pull tkinter in
    src = open(os.path.join(os.path.dirname(__file__), "..", "export.py")).read()
    assert "tkinter" not in src
    assert "import tk" not in src


def test_build_song_lines_reads_meta_from_doc_not_a_ui():
    doc = _doc_with_one_section()
    lines = export.build_song_lines(doc)
    text = "\n".join(lines)
    assert "THIRD STATE" in text
    assert "20Minutes" in text
    assert "Key: B" in text
    assert "[Intro]" in text
    assert "Bass (4-string)" in text


def test_build_song_lines_filters_by_instrument():
    doc = _doc_with_one_section()
    sec2 = model.new_section("v1", "Verse", "Verse",
                              instrument="Guitar (6-string)")
    sec2["items"] = [model.make_token("Am", None)]
    doc["sections"].append(sec2)

    bass_only = "\n".join(export.build_song_lines(doc, instruments={"Bass (4-string)"}))
    assert "[Intro]" in bass_only
    assert "[Verse]" not in bass_only

    both = "\n".join(export.build_song_lines(doc, instruments=None))
    assert "[Intro]" in both
    assert "[Verse]" in both


def test_build_song_lines_empty_doc_still_has_footer():
    doc = model.new_document(title="Untitled")
    lines = export.build_song_lines(doc)
    assert any("Generated by Song Notation Tool" in ln for ln in lines)


def test_build_pdf_returns_valid_pdf_bytes():
    doc = _doc_with_one_section()
    pdf_bytes = export.build_pdf(doc)
    assert pdf_bytes.startswith(b"%PDF-1.4")
    assert b"%%EOF" in pdf_bytes


def test_build_pdf_orientation_changes_page_size():
    doc = _doc_with_one_section()
    portrait = export.build_pdf(doc, orient="portrait")
    landscape = export.build_pdf(doc, orient="landscape")
    assert b"[0 0 842.00 595.00]" in landscape  # landscape MediaBox
    assert b"[0 0 595.00 842.00]" in portrait    # portrait MediaBox


def test_default_export_name_uses_artist_and_title():
    from constants import default_export_name
    doc = _doc_with_one_section()
    assert default_export_name(doc, "txt") == "20Minutes_-_Third_State.txt"
    doc["meta"]["artist"] = ""
    assert default_export_name(doc, ".pdf") == "Third_State.pdf"
